[Unit]
RequiresMountsFor=/var/lib/caddy

[Service]
Environment=HOME=/var/lib/caddy
RuntimeDirectory=caddy
RuntimeDirectoryMode=0750
ExecStartPre=+/usr/lib/homeharbor/agent/HomeHarbor.Agent ensure-caddy-config
ExecStart=
ExecStart=/usr/bin/caddy run --environ --config /var/lib/homeharbor-caddy/Caddyfile
ExecReload=
ExecReload=/usr/bin/caddy reload --address unix//run/caddy/admin.sock --config /var/lib/homeharbor-caddy/Caddyfile --force
