post_install() {
  if [[ ! -e /etc/selinux/config ]]; then
    ln -s config.refpolicy-arch /etc/selinux/config
  fi

  echo 'Building the HomeHarbor refpolicy-arch policy store...'
  semodule --noreload -s refpolicy-arch -i /usr/share/selinux/refpolicy-arch/*.pp
}

post_upgrade() {
  post_install
}

post_remove() {
  rm -rf /etc/selinux/refpolicy-arch
  if [[ -L /etc/selinux/config && ! -e /etc/selinux/config ]]; then
    rm /etc/selinux/config
  fi
}
