#!/bin/bash

build() {
  add_module dm_mod
  add_module dm_crypt
  add_module dm_verity
  add_module md_mod
  add_module raid456
  add_module erofs
  add_module loop
  add_module overlay
  add_module ext4
  add_module btrfs
  add_module xfs
  add_binary chattr
  add_binary cryptsetup
  add_binary dmsetup
  add_binary lpdump
  add_binary mdadm
  add_binary /boot/init/homeharbor-verity
  add_binary /usr/lib/homeharbor/homeharbor-avb
  add_binary sha256sum
  add_binary mount
  add_binary umount
  add_binary veritysetup
  map add_udev_rule \
    '10-dm.rules' \
    '13-dm-disk.rules' \
    '95-dm-notify.rules'
  add_runscript
}

help() {
  cat <<HELPEOF
Opens the HomeHarbor EROFS root, modules, and firmware selected by the OTA-maintained boot environment.
Kernel parameters:
  root=/dev/mapper/homeharbor-root
  homeharbor.super=/dev/disk/by-partlabel/super
  homeharbor.boot_state=/dev/disk/by-label/state
  homeharbor.boot_generic=1
  homeharbor.recovery=1
HELPEOF
}
